; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs =
	LILYGO_T5_V231
description = Monitor e-ink to show current temperature of Smart-Swimmingpool.

[common]
serial_speed = 115200

[env:LILYGO_T5_V231]
platform = espressif32 @ 7.0.1
board = esp32dev
framework = arduino
lib_deps =
	adafruit/Adafruit BusIO @ ^1.16.1
	adafruit/Adafruit GFX Library @ ^1.11.11
	zinggjm/GxEPD @ ^3.1.1
	juerd/ESP-WiFiSettings @ ^3.9.2
	olikraus/U8g2 @ ^2.35.30
	olikraus/U8g2_for_Adafruit_GFX @ ^1.8.0
	knolleary/PubSubClient @ ^2.8
	arduino-libraries/NTPClient @ ^3.2.1
	jchristensen/Timezone @ ^1.2.4
	bblanchon/ArduinoJson @ ^7.3.2
build_flags =
	${env.build_flags}
	; FW_VERSION is auto-maintained by release-please — do not edit manually
	'-DFW_VERSION="0.1.0"'
	'-DGITHUB_REPO="smart-swimmingpool/monitor"'
	-D SERIAL_SPEED=${common.serial_speed}
	-D LILYGO_T5_V231
	-std=gnu++11
	-Wno-deprecated-declarations
upload_speed = ${common.serial_speed}
monitor_speed = ${common.serial_speed}
monitor_filters = esp32_exception_decoder, time, default
test_ignore = test_desktop
board_build.filesystem = littlefs
